/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.inria.soctrace.tools.ocelotl.core.lpaggreg.jni;

public class lpaggregJNI {
	public final static native void delete_LPAggregWrapper(long jarg1);

	public final static native void delete_MLPAggregWrapper(long jarg1);

	public final static native void delete_VLPAggregWrapper(long jarg1);

	public final static native void LPAggregWrapper_computeDichotomy(long jarg1, LPAggregWrapper jarg1_, float jarg2);

	public final static native void LPAggregWrapper_computeParts(long jarg1, LPAggregWrapper jarg1_, float jarg2);

	public final static native void LPAggregWrapper_computeQualities(long jarg1, LPAggregWrapper jarg1_, boolean jarg2);

	public final static native double LPAggregWrapper_getGainByIndex(long jarg1, LPAggregWrapper jarg1_, int jarg2);

	public final static native double LPAggregWrapper_getGainByParameter(long jarg1, LPAggregWrapper jarg1_, float jarg2);

	public final static native double LPAggregWrapper_getLossByIndex(long jarg1, LPAggregWrapper jarg1_, int jarg2);

	public final static native double LPAggregWrapper_getLossByParameter(long jarg1, LPAggregWrapper jarg1_, float jarg2);

	public final static native float LPAggregWrapper_getParameter(long jarg1, LPAggregWrapper jarg1_, int jarg2);

	public final static native int LPAggregWrapper_getParameterNumber(long jarg1, LPAggregWrapper jarg1_);

	public final static native int LPAggregWrapper_getPart(long jarg1, LPAggregWrapper jarg1_, int jarg2);

	public final static native int LPAggregWrapper_getPartNumber(long jarg1, LPAggregWrapper jarg1_);

	public final static native void MLPAggregWrapper_addToMatrix__SWIG_0(long jarg1, MLPAggregWrapper jarg1_, double jarg2, int jarg3);

	public final static native void MLPAggregWrapper_addToMatrix__SWIG_1(long jarg1, MLPAggregWrapper jarg1_, double jarg2, int jarg3, int jarg4);

	public final static native void MLPAggregWrapper_addToVector__SWIG_0(long jarg1, MLPAggregWrapper jarg1_, double jarg2);

	public final static native void MLPAggregWrapper_addToVector__SWIG_1(long jarg1, MLPAggregWrapper jarg1_, double jarg2, int jarg3);

	public final static native void MLPAggregWrapper_computeDichotomy(long jarg1, MLPAggregWrapper jarg1_, float jarg2);

	public final static native void MLPAggregWrapper_computeParts(long jarg1, MLPAggregWrapper jarg1_, float jarg2);

	public final static native void MLPAggregWrapper_computeQualities(long jarg1, MLPAggregWrapper jarg1_, boolean jarg2);

	public final static native int MLPAggregWrapper_getMatrixNumber(long jarg1, MLPAggregWrapper jarg1_);

	public final static native int MLPAggregWrapper_getMatrixSize(long jarg1, MLPAggregWrapper jarg1_);

	public final static native int MLPAggregWrapper_getVectorSize(long jarg1, MLPAggregWrapper jarg1_);

	public final static native void MLPAggregWrapper_newMatrix(long jarg1, MLPAggregWrapper jarg1_);

	public final static native void MLPAggregWrapper_newVector(long jarg1, MLPAggregWrapper jarg1_);

	public final static native long MLPAggregWrapper_SWIGUpcast(long jarg1);

	public final static native long new_MLPAggregWrapper();

	public final static native long new_VLPAggregWrapper();

	public final static native void VLPAggregWrapper_addToVector__SWIG_0(long jarg1, VLPAggregWrapper jarg1_, double jarg2);

	public final static native void VLPAggregWrapper_addToVector__SWIG_1(long jarg1, VLPAggregWrapper jarg1_, double jarg2, int jarg3);

	public final static native void VLPAggregWrapper_computeDichotomy(long jarg1, VLPAggregWrapper jarg1_, float jarg2);

	public final static native void VLPAggregWrapper_computeParts(long jarg1, VLPAggregWrapper jarg1_, float jarg2);

	public final static native void VLPAggregWrapper_computeQualities(long jarg1, VLPAggregWrapper jarg1_, boolean jarg2);

	public final static native int VLPAggregWrapper_getVectorNumber(long jarg1, VLPAggregWrapper jarg1_);

	public final static native int VLPAggregWrapper_getVectorSize(long jarg1, VLPAggregWrapper jarg1_);

	public final static native void VLPAggregWrapper_newVector(long jarg1, VLPAggregWrapper jarg1_);

	public final static native long VLPAggregWrapper_SWIGUpcast(long jarg1);
}
