/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.inria.soctrace.tools.ocelotl.core.lpaggreg.jni;

public class MLPAggregWrapper extends LPAggregWrapper {
  private long swigCPtr;

  protected MLPAggregWrapper(long cPtr, boolean cMemoryOwn) {
    super(lpaggregJNI.MLPAggregWrapper_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MLPAggregWrapper obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        lpaggregJNI.delete_MLPAggregWrapper(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MLPAggregWrapper() {
    this(lpaggregJNI.new_MLPAggregWrapper(), true);
  }

  public void newMatrix() {
    lpaggregJNI.MLPAggregWrapper_newMatrix(swigCPtr, this);
  }

  public void addToMatrix(double element, int i) {
    lpaggregJNI.MLPAggregWrapper_addToMatrix__SWIG_0(swigCPtr, this, element, i);
  }

  public void addToMatrix(double element, int i, int j) {
    lpaggregJNI.MLPAggregWrapper_addToMatrix__SWIG_1(swigCPtr, this, element, i, j);
  }

  public void newVector() {
    lpaggregJNI.MLPAggregWrapper_newVector(swigCPtr, this);
  }

  public void addToVector(double element) {
    lpaggregJNI.MLPAggregWrapper_addToVector__SWIG_0(swigCPtr, this, element);
  }

  public void addToVector(double element, int index) {
    lpaggregJNI.MLPAggregWrapper_addToVector__SWIG_1(swigCPtr, this, element, index);
  }

  public void computeQualities(boolean normalization) {
    lpaggregJNI.MLPAggregWrapper_computeQualities(swigCPtr, this, normalization);
  }

  public void computeParts(float parameter) {
    lpaggregJNI.MLPAggregWrapper_computeParts(swigCPtr, this, parameter);
  }

  public void computeDichotomy(float threshold) {
    lpaggregJNI.MLPAggregWrapper_computeDichotomy(swigCPtr, this, threshold);
  }

  public int getMatrixNumber() {
    return lpaggregJNI.MLPAggregWrapper_getMatrixNumber(swigCPtr, this);
  }

  public int getMatrixSize() {
    return lpaggregJNI.MLPAggregWrapper_getMatrixSize(swigCPtr, this);
  }

  public int getVectorSize() {
    return lpaggregJNI.MLPAggregWrapper_getVectorSize(swigCPtr, this);
  }

}
