/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.inria.soctrace.tools.ocelotl.core.lpaggreg.jni;

public class LPAggregWrapper {
	protected static long getCPtr(final LPAggregWrapper obj) {
		return obj == null ? 0 : obj.swigCPtr;
	}

	private long		swigCPtr;

	protected boolean	swigCMemOwn;

	protected LPAggregWrapper(final long cPtr, final boolean cMemoryOwn) {
		swigCMemOwn = cMemoryOwn;
		swigCPtr = cPtr;
	}

	public void computeDichotomy(final float threshold) {
		lpaggregJNI.LPAggregWrapper_computeDichotomy(swigCPtr, this, threshold);
	}

	public void computeParts(final float parameter) {
		lpaggregJNI.LPAggregWrapper_computeParts(swigCPtr, this, parameter);
	}

	public void computeQualities(final boolean normalization) {
		lpaggregJNI.LPAggregWrapper_computeQualities(swigCPtr, this, normalization);
	}

	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				lpaggregJNI.delete_LPAggregWrapper(swigCPtr);
			}
			swigCPtr = 0;
		}
	}

	@Override
	protected void finalize() {
		delete();
	}

	public double getGainByIndex(final int index) {
		return lpaggregJNI.LPAggregWrapper_getGainByIndex(swigCPtr, this, index);
	}

	public double getGainByParameter(final float parameter) {
		return lpaggregJNI.LPAggregWrapper_getGainByParameter(swigCPtr, this, parameter);
	}

	public double getLossByIndex(final int index) {
		return lpaggregJNI.LPAggregWrapper_getLossByIndex(swigCPtr, this, index);
	}

	public double getLossByParameter(final float parameter) {
		return lpaggregJNI.LPAggregWrapper_getLossByParameter(swigCPtr, this, parameter);
	}

	public float getParameter(final int index) {
		return lpaggregJNI.LPAggregWrapper_getParameter(swigCPtr, this, index);
	}

	public int getParameterNumber() {
		return lpaggregJNI.LPAggregWrapper_getParameterNumber(swigCPtr, this);
	}

	public int getPart(final int index) {
		return lpaggregJNI.LPAggregWrapper_getPart(swigCPtr, this, index);
	}

	public int getPartNumber() {
		return lpaggregJNI.LPAggregWrapper_getPartNumber(swigCPtr, this);
	}

}
