/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package fr.inria.soctrace.tools.ocelotl.core.lpaggreg.jni;

public class VLPAggregWrapper extends LPAggregWrapper {
	protected static long getCPtr(final VLPAggregWrapper obj) {
		return obj == null ? 0 : obj.swigCPtr;
	}

	private long	swigCPtr;

	public VLPAggregWrapper() {
		this(lpaggregJNI.new_VLPAggregWrapper(), true);
	}

	protected VLPAggregWrapper(final long cPtr, final boolean cMemoryOwn) {
		super(lpaggregJNI.VLPAggregWrapper_SWIGUpcast(cPtr), cMemoryOwn);
		swigCPtr = cPtr;
	}

	public void addToVector(final double element) {
		lpaggregJNI.VLPAggregWrapper_addToVector__SWIG_0(swigCPtr, this, element);
	}

	public void addToVector(final double element, final int index) {
		lpaggregJNI.VLPAggregWrapper_addToVector__SWIG_1(swigCPtr, this, element, index);
	}

	@Override
	public void computeDichotomy(final float threshold) {
		lpaggregJNI.VLPAggregWrapper_computeDichotomy(swigCPtr, this, threshold);
	}

	@Override
	public void computeParts(final float parameter) {
		lpaggregJNI.VLPAggregWrapper_computeParts(swigCPtr, this, parameter);
	}

	@Override
	public void computeQualities(final boolean normalization) {
		lpaggregJNI.VLPAggregWrapper_computeQualities(swigCPtr, this, normalization);
	}

	@Override
	public synchronized void delete() {
		if (swigCPtr != 0) {
			if (swigCMemOwn) {
				swigCMemOwn = false;
				lpaggregJNI.delete_VLPAggregWrapper(swigCPtr);
			}
			swigCPtr = 0;
		}
		super.delete();
	}

	@Override
	protected void finalize() {
		delete();
	}

	public int getVectorNumber() {
		return lpaggregJNI.VLPAggregWrapper_getVectorNumber(swigCPtr, this);
	}

	public int getVectorSize() {
		return lpaggregJNI.VLPAggregWrapper_getVectorSize(swigCPtr, this);
	}

	public void newVector() {
		lpaggregJNI.VLPAggregWrapper_newVector(swigCPtr, this);
	}

}
